#!/usr/bin/env python3
try:	import colors as c
except ImportError:	import skilstak.colors as c
import os
import pwd
import unames as un
from sys import argv

# This simply allows you to put in a message, and it will send it to
# an "announcement" file in everyone's bin.

user = pwd.getpwuid(os.getuid()).pw_name
path = '/home/' + user + '/announcement'
usage = '''{}Puts a python file in someone's bin!
Usage:
{}- {}announce <options>
{}Options:
• {}-all {}Sends message to all users
{}• {}-u <user> {}Sends message to specific user'''.format(c.g,c.g,c.cyan,c.g,c.cyan,c.g,c.g,c.cyan,c.g)

def writefile():
	os.system('touch ' + path)
		
	# Initial Setup Stuff
	os.system('echo "#!/usr/bin/env python3" >> ' + path)
	os.system('echo "try: import colors as c" >> ' + path)
	os.system('echo "except ImportError: import skilstak.colors as c" >> ' + path)
	os.system('echo "import os" >> ' + path)
	os.system('echo "" >> ' + path)

	# The message variable
	os.system("""echo "message = '""" + str(message) + """'" >> """ + path)
	os.system('echo "" >> ' + path)

	# The delete confirmation functionA
	os.system('''echo "def confirmdel():" >> ''' + path)
	os.system('''echo "    delete = input(c.red + '> ' + c.cyan).lower()" >> ''' + path)
	os.system('''echo "    if delete == 'yes':" >> ''' + path)
	os.system('''echo "        print(c.g + 'Deleting...')" >> ''' + path)
	os.system('''echo "        os.system('rm ~/repos/multiuser/exannounce')" >> ''' + path)
	os.system('''echo "    elif delete == 'no':" >> ''' + path)
	os.system('''echo "        print(c.g + 'Okay, but if another announcement comes around, stuff will break!')" >> ''' + path)
	os.system('''echo "        exit()" >> ''' + path)
	os.system('''echo "    else:" >> ''' + path)
	os.system('''echo "        print(c.red + 'Sorry, not an answer. Try "yes" or "no".')" >> ''' + path)
	os.system('''echo "        confirmdel()" >> ''' + path)
	os.system('''echo "\n" >> ''' + path)

	# The main printing thing
	os.system('''echo "print(c.g + 'Oops, we got a message!')" >> ''' + path)
	os.system('''echo "print(c.g + 'Here it is:')" >> ''' + path)
	os.system('''echo "print(c.magenta + message)" >> ''' + path)
	os.system('''echo "print()" >> ''' + path)
	os.system('''echo "print(c.g + 'Would you like to delete it?')" >> ''' + path)
	os.system('''echo "confirmdel()" >> ''' + path)

	# Almost done, chmods the file
	os.system('chmod +x ' + path)

	# Logs out
	os.system('exit')

def prompt():
	print(c.g + 'Enter your message:')
	message = input(c.cyan)


if os.getuid() != 0:
    print(c.r + 'Need to run with root privleges!')
else:

	if len(argv) == 3:
		pass
	else:
		print(usage)

