#!/usr/bin/env python3
import colors as c
import os
# This simply allows you to put in a message, and it will send it to
# an "announcement.txt" file in everyone's bin.

path = '~/repos/multiuser/qannouncement'

print(c.g + 'Enter your message')
message = input(c.cyan)

# Initial Setup Stuff
os.system('echo "#!/usr/bin/env python3\n" >> ' + path)
os.system('echo "import colors as c"\n >> ' + path)
os.system('echo "import os"\n >> ' + path)
os.system('echo "\n" >> ' + path)

# The message variable
os.system("""echo "message = '""" + str(message) + """'\n" >> """ + path)
os.system('\n >> ' + path)

# The delete confirmation function
os.system('''echo "confirmdel():\n" >> ''' + path)
os.system('''echo "    delete = input(c.red + '>' + c.cyan).lower()\n" >> ''' + path)
os.system('''echo "    if delete == 'yes':\n" >> ''' + path)
os.system('''echo "        print(c.g + 'Deleting...')\n" >> ''' + path)
os.system('''echo "        os.system('rm ~/repos/multiuser/qannouncement')\n" >> ''' + path)
os.system()
os.system()
os.system()








os.system('''echo "print(test)" >> ''' + path)
os.system('chmod +x ' + path)
