#!/usr/bin/env python3
import sys
import colors as c

usage = c.green + '''
Arguments:''' + c.cyan + '''
- troll <user>
- eat <user>
- barf <user>
- nuke <user>
'''

if len(sys.argv) >= 2:
	print('Arrrrrrrrrggs detected!')
	if sys.argv[2] == 'troll':
		print(c.cyan + sys.argv[3] + c.green + ' has been trolled!')
	else:
		print(usage)
else:
	print(usage)