#!/usr/bin/env python3
try:	import colors as c
except:	import skilstak.colors as c
import os
import unames as un
import sysadmins as sysad

def confirmcreate():
	createit = input(c.red + '> ' + c.cyan)
	if createit == 	'y' or createit == 'yes':
		# Git clone the home-config
		os.system('cd /home/' + username + '/repos/')
		os.system('git clone https://github.com/rydens/home-config')
		# Will still have to run './setup' manually, though
	else:
		pass
			

# Needs to be run with sudo!
if os.getuid() != 0:
    print(c.r + 'Need to run with root privleges!')
else:
	print(c.green + 'Updating all home-configs...')
	
	# Removes admins from the list of people to update
	for sysadmin in sysad.sysadmins:
		if sysadmin in un.usernames:
			un.usernames.remove(sysadmin)

	# Logs in to each user, then checks for the file.
	# Tries to make it if it doesn't exist
	for username in un.usernames:
		if os.path.exists('/home/' + username + '/repos/home-config'):
			os.system('cd /home/' + username + '/repos/')
			os.system('rm -rf home-config/')
			os.system('git clone https://github.com/rydens/home-config.git')
			os.system('cd home-config; . bashrc')
			print(c.cyan + str(username) + c.base3 + "'s home-config was updated!")
		else:
			print(c.cyan + str(username) + c.red + "'s home-config could not be found.")
			print(c.green + 'Should we create it for them?')
			confirmcreate()