#!/usr/bin/env python3
try:	import colors as c
except ImportError:	import skilstak.colors as c
import os
from sys import argv

usage = c.g + '''Makes a new subdomain for nginx, then adds a letsencrypt.org HTTPS certificate!
Usage:
newsubdomain <{}domain{}> <{}subdomain name{}> <{}root for it{}> <{}name of conf file{}>'''.format(c.m,c.cyan,c.m,c.cyan,c.m,c.cyan,c.m,c.cyan)

def makesubdomain():
	os.system('sudo service nginx stop')
	os.system('sudo letsencrypt certonly --standalone -d ' + argv[2] + '.' + argv[1] + ' -d www.' + argv[2] + '.' + argv[1])
	os.system('''echo "server {" >> /etc/nginx/sites-available''' + argv[4])
	os.system('''echo "  listen 443 ssl;" >> /etc/nginx/sites-available/''' + argv[4])
	os.system('''echo "  ssl_certificate /etc/letsencryt/live/{}.{}/fullchain.pem;" >> /etc/nginx/sites-available/'''.format(argv[2],argv[1]) + argv[4])
	os.system('''echo "  ssl_certificate_key /etc/letsencrypt/live/{}.{}/privkey.pem;" >> /etc/nginx/sites-available/'''.format(argv[2],argv[1]) + argv[4])
	os.system('''echo "  server_name {}.{};" >> /etc/nginx/sites-available/'''.format(argv[2],argv[1]) + argv[4])
	os.system('''echo "  root {};" >> /etc/nginx/sites-available/'''.format(argv[3]) + argv[4])
	os.system('''echo "  location / {" >> /etc/nginx/sites-available/''' + argv[4])
	os.system('''echo "    index index.html;" >> /etc/nginx/sites-available/''' + argv[4])
	os.system('''echo "  }" >> /etc/nginx/sites-available/''' + argv[4])
	os.system('''echo "}\n" >> /etc/nginx/sites-available/''' + argv[4])
	os.system('sudo service nginx start')
	exit()

if os.getuid() != 0:
    print(c.r + 'Need to run with root privleges!')
else:
	
	if len(argv) = 5:
		if argv[1] == '-h' or argv[1] == '-help' or argv[1] == 'help' or argv[1] == 'h':
			print(usage)
		else:
			if os.path.exists(argv[3]):
				if os.path.exists('/etc/nginx/sites-available/' + argv[4]):
					makesubdomain()
				else:
					print(c.r + 'Configurations file not found!')
					exit()
			else:
				print(c.r + 'Root area not found!')
				exit()
	else:
		print(usage)

