#!/usr/bin/env python3
# Push, NOW WITH ARGUMENTS :D
import os
import pwd
import colors as c
from sys import argv


uname = pwd.getpwuid(os.getuid()).pw_name
usage = c.g + '''Pushes the contents of the current directory to whereever you want!
Usage:''' + c.r + '''
- ''' + c.cyan + '''push1 <''' + c.m + '''destination''' + c.cyan + '''>''' + c.r + '''
- ''' + c.cyan + '''Default destination: ''' + c.m + '''/var/www/html/''' + uname + '''/'''

if len(argv) >= 2:
	if os.path.exists(argv[1]):
		os.system('rm -rf ' + argv[1] + '/*')
else:
	print(usage)