#!/usr/bin/env python3
# Push, NOW WITH ARGUMENTS :D
import os
import pwd
from sys import argv
try:	import colors as c
except ImportError:	import skilstak.colors as c


uname = pwd.getpwuid(os.getuid()).pw_name

usage = c.g + '''Pushes the contents of the current directory to whereever you want!
Usage:''' + c.r + '''
- ''' + c.cyan + '''push <''' + c.m + '''destination''' + c.cyan + '''>''' + c.r + '''
- ''' + c.cyan + '''Default destination: ''' + c.m + '''/var/www/html/''' + uname + '''/''' + c.r + '''
- ''' + c.cyan + '''Use ''' + c.m + '''push1 default''' + c.cyan + ''' for default destination.'''

confirmation = '''You just shoved a file… *sigh*, what did that file do to you? HUH? 
What makes you think that it was ok to shove it? Was it because you don't think it has feelings? 
That you’re better than it? Or are you just an over confident piece of trash? 
Whatever you are, you should stop because every 20 seconds a file gets pushed, it 
becomes depressed and separates it from its other file family. AND YOU ARE THE REASON! 
Look at what you’ve done, I bet you didn’t think twice about sending that file away! 
It will probably never see its family, or friends, ever again. Some people just don't understand 
what it’s like. What if you were put on the spotlight and then sent away never to return, how would you feel? 
You’re just so disgusting! I can’t even look at you! Just go away and never do it again!'''


if len(argv) >= 2:
	if os.path.exists(argv[1]):
		os.system('rm -rf ' + argv[1] + '/*')
		os.system('cp -r ./* ' + argv[1] + '/')
		print(c.m + confirmation)
	elif argv[1] == 'default':
		os.system('rm -rf /var/www/html/' + uname + '/*')
		os.system('cp -r ./* /var/www/html/' + uname + '/')
	else:
		print(c.r + 'Directory not found!')
		print(usage)
else:
	print(usage)